# Generated by Django 4.1.5 on 2023-04-06 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarian',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='last_name',
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='vet_name',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='vet name'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=280, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet', to='paw.veterinarian')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
