# Generated by Django 4.1.5 on 2023-04-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw', '0002_remove_veterinarian_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='vet_name',
            field=models.CharField(default='no name', max_length=80, unique=True, verbose_name='vet name'),
        ),
    ]
