# Generated by Django 4.1.5 on 2023-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw', '0009_appointment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=80, unique=True, verbose_name='client_name'),
        ),
    ]
