# Generated by Django 4.1.5 on 2023-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw', '0012_alter_appointment_client_alter_appointment_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='notes',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
