# Generated by Django 4.1.5 on 2023-06-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paw', '0014_client_created_by_pet_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet', to='paw.veterinarian'),
        ),
    ]
